version: '3.4'

services:
  accenture_backend_test:
    image: accenture_backend_test
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
